config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'sites#index', as: :unauthenticated_root
  end

  resources :banks
  resources :contacts
  resources :medicines
  resources :adoptions, only: :index
  resources :animals do
    member do
      patch :adoption
    end
  end
  resources :sites do
    member do
      get :animal_history
    end
  end
end

app/models/medicine.rb
# frozen_string_literal: true

class Medicine < ApplicationRecord
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :name, presence: true, uniqueness: { case_sensitive: false }


  def self.ransackable_attributes(auth_object = nil)
    ['name']
  end

  def self.ransackable_associations(auth_object = nil)
    ["name"]
  end
end

app/controllers/medicines_controller.rb
# frozen_string_literal: true

class MedicinesController < ApplicationController
  before_action :set_medicine, only: %i[show edit update destroy]

  def index
    @q = Medicine.ransack(params[:q])
    @medicines = @q.result(district: true).page(params[:page])
  end

  def show; end

  def new
    @medicine = Medicine.new
  end

  def edit; end

  def create
    @medicine = Medicine.new(medicine_params)
    if @medicine.save
      redirect_to medicines_path, notice: 'Medicamento adicionado com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @medicine.update(medicine_params)
      redirect_to medicines_path, notice: 'Medicamento atualizado com sucesso.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @medicine.destroy
    redirect_to medicines_url, notice: 'Medicamento excluido.'
  end

  private

  def set_medicine
    @medicine = Medicine.find(params[:id])
  end

  def medicine_params
    params.require(:medicine).permit(:name, :quantity)
  end
end

app/helpers/medicines_helper.rb
# frozen_string_literal: true

module MedicinesHelper
end

app/views/medicines/_form.html.erb
<div class='px-2 py-5 sm:px-6'>
    <%= form_for @medicine, url: url, html: { class: 'space-y-6' }, data: { turbo: :false } do |f| %>
      <div class='px-3 mb-2'>
        <%= label_tag :name, 'Nome', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.text_field :name,
                          autofocus: true,
                          required: true,
                          class: 'appearance-none block w-full px-3 py-2 border border-gray-300
                                  rounded-md shadow-sm mb-4 placeholder-gray-400 focus:outline-none
                                  focus:ring-orange-400 focus:border-orange-500 sm:text-sm' %>


        <%= f.label :quantity, 'Quantidade', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.number_field :quantity,
                        autofocus: true,
                          class: 'appearance-none block w-full px-3 py-2 border border-gray-300
                          rounded-md shadow-sm mb-4 placeholder-gray-400 focus:outline-none
                          focus:ring-orange-400 focus:border-orange-500 sm:text-sm' %>

      <%= link_to "Voltar", medicines_path, class:"button-secondary" %>
      <%= f.submit "Concluido", class:"button-primary" %>
      </div>

    <% end %>
</div>

app/views/medicines/_search_bar.html.erb
<div class="p-4">
  <label for="table-search" class="sr-only">Search</label>
  <div class="flex justify-end">
    <div class="relative mt-1">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
            clip-rule="evenodd"></path>
        </svg>
      </div>
      <%= search_form_for @q do |f| %>
        <%= f.search_field :name_cont, class: "search-input", placeholder: "Pesquisar..." %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/medicines/_search_input.html.erb
<div class="p-4">
  <label for="table-search" class="sr-only">Search</label>
  <div class="flex justify-end">
    <div class="relative mt-1">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
            clip-rule="evenodd"></path>
        </svg>
      </div>
      <%= search_form_for @q do |f| %>
        <%= f.search_field :name_cont, class: "search-input", placeholder: "Pesquisar..." %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/medicines/_table.html.erb
<div class="relative overflow-x-auto">
 <table class="w-full text-sm text-left text-gray-500 shadow-lg rounded-lg">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3">
                Nome
            </th>
            <th scope="col" class="px-6 py-3">
                Quantidade
            </th>
             <th scope="col" class="px-6 py-3">
            </th>
             <th scope="col" class="px-6 py-3">
            </th>
          </tr>
      </thead>
      <tbody>
        <% @medicines.each do |medicine| %>
          <tr class="bg-white border-b">
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                <%= medicine.name %>
            </th>
            <td class="px-6 py-4">
                <%= medicine.quantity %>
            </td>
            <td class="px-6 py-4 text-end">
                <%= link_to edit_medicine_path(medicine),
                  class: 'font-semibold link-color hover:underline' do %>
                  Atualizar
                <% end %>
            </td>
            <td class="px-6 py-4 text-end">
                <%= button_to medicine_path(medicine), method: :delete,
                  class: 'text-red-500 hover:text-black hover:underline' do %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

app/views/medicines/edit.html.erb
<div class='bg-gray-100 rounded-lg space-y-4 w-1/2 mx-auto'>
  <div class="bg-white rounded-lg p-2 shadow-lg">
    <h1 class="text-3xl font-bold ml-2 my-2">Adicionar ou remover medicamento</h1>
  </div>
  <div class="bg-white rounded-lg p-2 shadow-lg">
    <%= render 'form', url: medicine_path(@medicine) %>
  </div>
</div>

app/views/medicines/index.html.erb
<div class="w-full">
  <div class="flex justify-between bg-white items-center rounded-lg p-4">
    <div>
      <h1 class="md:text-4xl font-bold ">💉 Medicamentos</h1>
    </div>
    <div>
      <%= link_to "Adicionar medicamento", new_medicine_path, class: "bg-black text-white md:p-2 text-xs p-1.5 rounded-lg" %>
    </div>
  </div>
  <div class="md:flex md:justify-beetween md:items-center">
    <div class="hidden md:block">
        <%= paginate @medicines %>
    </div>
    <div class="md:ml-auto flex justify-center">
      <%= render 'search_input' %>
    </div>
  </div>
  <%= render 'table' %>
  <div class="md:hidden flex justify-center">
    <%= paginate @medicines, window: 1 %>
  </div>
</div>

app/views/medicines/new.html.erb
<div class='bg-gray-100 rounded-lg space-y-4 md:w-1/2 w-full mx-auto'>
  <div class="bg-white rounded-lg p-2 shadow-lg">
    <h1 class="text-xl md:text-3xl font-bold ml-2 my-2">Criar medicamento</h1>
  </div>
  <div class="bg-white rounded-lg p-2 shadow-lg">
    <%= render 'form', url: medicines_path %>
  </div>
</div>