config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'sites#index', as: :unauthenticated_root
  end

  resources :banks
  resources :contacts
  resources :medicines
  resources :adoptions, only: :index
  resources :animals do
    member do
      patch :adoption
    end
  end
  resources :sites do
    member do
      get :animal_history
    end
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
    <div
      id="toast-success"
      class="transition transform duration-1000 hidden fixed absolute top-5 right-5 flex items-center max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow"
      role="alert"
      data-controller="notification"
      data-notification-delay-value="3000"
      data-transition-enter-from="opacity-0 translate-x-6"
      data-transition-enter-to="opacity-100 translate-x-0"
      data-transition-leave-from="opacity-100 translate-x-0"
      data-transition-leave-to="opacity-0 translate-x-6"
      >
      <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
          <span class="sr-only">Check icon</span>
      </div>
      <div class="ml-3 text-sm font-normal mr-3"><%= value %></div>
      <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8" data-dismiss-target="#toast-success" aria-label="Close">
          <span class="sr-only">Close</span>
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white">
    <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
        <div class="flex md:justify-between justify-center mx-auto">
          <div class="mb-6 md:mb-0">
              <a href="#" class="flex items-center">
                <%= image_tag "logo.png", class: "h-32" %>
              </a>
          </div>
          <div class="grid grid-cols-1 gap-8 sm:gap-6 sm:grid-cols-2">
              <div>
                <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase">Nossas redes</h2>
                <ul class="text-gray-500 font-medium">
                    <li class="mb-4">
                        <a href="https://www.facebook.com/novo.caminho.batatais" class="hover:underline ">Facebook</a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/ong.novocaminho/" class="hover:underline">Instagram</a>
                    </li>
                </ul>
              </div>
          </div>
      </div>
      <hr class="my-6 border-gray-200 sm:mx-auto lg:my-8" />
      <div class="sm:flex sm:items-center sm:justify-between">
          <span class="text-sm text-gray-500 sm:text-center">© 2023 <a href="https://github.com/ericaraujo13" class="hover:underline">Desenvolvido por: Eric Araujo.</a>
          </span>
          <div class="flex mt-4 space-x-5 sm:justify-center sm:mt-0">
              <a href="https://www.facebook.com/novo.caminho.batatais" class="text-gray-500 hover:text-gray-900">
                  <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 8 19">
                        <path fill-rule="evenodd" d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z" clip-rule="evenodd"/>
                    </svg>
                  <span class="sr-only">Facebook</span>
              </a>
              <a href="https://www.instagram.com/ong.novocaminho/" class="text-gray-500 hover:text-gray-900">
                <span>
                    <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                      <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
                    </svg>
                </span>
                  <span class="sr-only">Instagram</span>
              </a>
          </div>
      </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-white shadow-lg m-2 rounded-lg">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-2">
  <a class="flex items-center">
    <div class="absolute left-5 self-center font-semibold whitespace-nowrap flex items-center">
      <%= image_tag "logo-pawn.png", class: "h-20" %>
      <h1 class="hidden xl:block ml-2 text-xl text-black font-bold">Associação Novo Caminho</h1>
    </div>
  </a>
  <div class="flex md:order-2">
      <%= button_to destroy_user_session_path, method: :delete, class: "flex items-center mr-2 border border-black rounded-lg p-1.5 hover:bg-gray-100" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
        </svg>
      <% end %>
      <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 text-sm bg-black text-white rounded-lg md:hidden focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>
  </div>
  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-default">
    <ul class="flex flex-col font-medium p-2 space-y-4 md:space-y-0 lg:p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white md:p-2">
      <li>
        <%= link_to authenticated_root_path,
          class: "#{inactive_active_class_for(authenticated_root_path)} p-2 hover:bg-red-500 rounded-lg hover:text-white" do %>
              Inicio
        <% end %>
      </li>
      <li>
        <%= link_to animals_path,
          class: "#{inactive_active_class_for(animals_path)} p-2 hover:bg-red-500 rounded-lg hover:text-white" do %>
              Animais
        <% end %>
      </li>
      <li>
        <%= link_to medicines_path,
          class: "#{inactive_active_class_for(medicines_path)} p-2 hover:bg-red-500 rounded-lg hover:text-white" do %>
              Medicamentos
        <% end %>
      </li>
      <li>
        <%= link_to adoptions_path,
          class: "#{inactive_active_class_for(adoptions_path)} p-2 hover:bg-red-500 rounded-lg hover:text-white" do %>
              Adoção
        <% end %>
      </li>
    </ul>
  </div>
  </div>
</nav>

app/views/shared/_site-navbar.html.erb
<nav class="bg-white border-gray-200 px-4">
    <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
        <%= link_to sites_path, class:"flex items-center" do %>
          <%= image_tag "logo.png", class: "h-16 md:h-32" %>
        <% end %>
        <div class="flex items-center">
          <%= link_to 'Entrar', new_user_session_path, class: "button-primary text-lg" %>
        </div>
    </div>
</nav>