config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'sites#index', as: :unauthenticated_root
  end

  resources :banks
  resources :contacts
  resources :medicines
  resources :adoptions, only: :index
  resources :animals do
    member do
      patch :adoption
    end
  end
  resources :sites do
    member do
      get :animal_history
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @recents = Bank.order(created_at: :desc).limit(6)
    @total_amount = Bank.balance
    @recent_adoptions = Animal.unavailable.order(updated_at: :desc).limit(6)
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/_cards.html.erb
<div class="flex flex-col md:flex-row space-x-5 items-center justify-center space-y-4">
  <div class="bg-red-100 w-full md:w-1/6 text-center md:mt-4 rounded-lg ml-4 h-full p-2 py-5 shadow-lg transition ease-in-out delay-50 hover:-translate-y-1 hover:scale-110 hover:bg-red-500 duration-300">
    <h1 class="font-bold">Residentes</h1>
    <p class="text-2xl font-bold"><%= Animal.count %></p>
  </div>
    <%= link_to banks_path, class: "bg-red-100 w-full md:w-1/6 text-center rounded-lg h-full p-2 py-5 shadow-lg transition ease-in-out delay-50 hover:-translate-y-1 hover:scale-110 hover:bg-red-500 duration-300" do %>
      <h1 class="font-bold">Caixa</h1>
      <p class="text-2xl font-bold"><%= number_to_currency(@total_amount, unit: 'R$', separator: ',', delimiter: '.', precision: 2).to_s.truncate(12, omission: "...") %></p>
    <% end %>
    <div class="bg-red-100 w-full md:w-1/6 text-center rounded-lg h-full p-2 py-5 shadow-lg transition ease-in-out delay-50 hover:-translate-y-1 hover:scale-110 hover:bg-red-500 duration-300">
      <h1 class="font-bold">Doentes</h1>
      <p class="text-2xl font-bold"><%= Animal.where(sick: "doente").count %></p>
    </div>
    <%= link_to contacts_path, class: "bg-red-100 w-full md:w-1/6 text-center rounded-lg h-full p-2 py-8 md:py-9 shadow-lg transition ease-in-out delay-50 hover:-translate-y-1 hover:scale-110 hover:bg-red-500 duration-300" do %>
      <h1 class="font-bold">Agenda</h1>
    <% end %>
</div>

app/views/home/_moneytab.html.erb
<div class="relative w-full overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500">
        <caption class="p-5 text-lg font-semibold text-gray-900 bg-white text-center">
            Fluxo de caixa
            <p class="mt-1 text-sm font-normal text-gray-500 "></p>
        </caption>
        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
                <th scope="col" class="px-4 py-3">
                    Titulo
                </th>
                <th scope="col" class="px-4 py-3">
                    Tipo
                </th>
                <th scope="col" class="hidden md:block px-4 py-3">
                    Data
                </th>
                <th scope="col" class="px-4 py-3">
                    Quantia
                </th>
                <th scope="col" class="px-4 py-3">
                  <span class="sr-only">Editar</span>
                </th>
            </tr>
        </thead>
        <tbody>
            <% @recents.each do |bank| %>
                <tr class="bg-white border-b">
                    <th scope="row" class="px-4 py-2 font-medium text-gray-900 whitespace-nowrap">
                        <%= bank.title %>
                    </th>
                    <td class="px-6 py-2 md:py-4">
                        <%= bank.category.humanize.capitalize %>
                    </td>
                    <td class="px-6 py-2 md:py-4 hidden md:block">
                    <%= bank.created_at.strftime("%d/%m/%Y") %>
                    </td>
                    <% if bank.category == 'entrada' %>
                        <td class="px-6 py-2 md:py-4 text-xs md:text-sm text-green-500">
                            + <%= number_to_currency(bank.amount) %>
                        </td>
                    <% else %>
                        <td class="px-6 py-2 md:py-4 text-red-500">
                            - <%= number_to_currency(bank.amount) %>
                        </td>
                    <% end %>
                    <td class="px-6 py-2 md:py-4 text-right">
                    <%= link_to edit_bank_path(bank), class: 'font-semibold text-black hover:text-gray-700 hover:underline' do %>
                      Atualizar
                    <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/home/_recent_adoptions.html.erb
<div class="relative w-full overflow-x-auto shadow-md sm:rounded-lg">
    <table class="text-sm w-full text-left text-gray-500">
        <caption class="p-5 text-lg font-semibold text-gray-900 bg-white text-center">
            Adoções recentes
            <p class="mt-1 text-sm font-normal text-gray-500 "></p>
        </caption>
        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Nome
                </th>
                <th scope="col" class="px-6 py-3">
                    Data
                </th>
                <th scope="col" class="px-6 py-3">
                    <span class="sr-only">Visualizar</span>
                </th>
            </tr>
        </thead>
        <tbody>
            <% @recent_adoptions.each do |animal| %>
                <tr class="bg-white border-b">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                        <%= animal.name %>
                    </th>
                    <td class="px-6 py-4">
                      <%= animal.updated_at.strftime("%d/%m/%Y") %>
                    </td>
                    <td class="px-6 py-4 text-right">
                      <%= link_to animal_path(animal), class: 'font-semibold link-color hover:underline' do %>
                        Visualizar
                      <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/home/index.html.erb
<div class="w-full max-h-screen">
  <div class="bg-white rounded-3xl p-8 mb-5">
    <h1 class="text-3xl font-bold mb-10">Bem vindo, <%= current_user.name %></h1>
    <hr class="my-10">
      <%= render 'cards' %>
    <hr class="my-10">
    <div class="grid grid-col gap-4 md:flex hidden md:block">
      <div class="w-1/2">
        <% if @recents.blank? %>
          <%= render 'moneytab' %>
          <p class="text-center text-gray-400 mt-4">Nenhum dado por enquanto.</p>
        <% else %>
          <%= render 'moneytab' %>
        <% end %>
      </div>
      <div class="w-1/2">
        <% if @recent_adoptions.blank? %>
          <%= render 'recent_adoptions' %>
          <p class="text-center text-gray-400 mt-4">Nenhum dado por enquanto.</p>
        <% else %>
          <%= render 'recent_adoptions' %>
        <% end %>
      </div>
    </div>
  </div>
</div>