config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'sites#index', as: :unauthenticated_root
  end

  resources :banks
  resources :contacts
  resources :medicines
  resources :adoptions, only: :index
  resources :animals do
    member do
      patch :adoption
    end
  end
  resources :sites do
    member do
      get :animal_history
    end
  end
end

app/models/animal.rb
# frozen_string_literal: true

class Animal < ApplicationRecord
  include AASM

  aasm timestamps: true do
    state :available, initial: true
    state :unavailable

    event :adopted do
      transitions from: :available, to: :unavailable
    end
  end

  enum gender: { macho: 0, fêmea: 1 }
  enum sick: { doente: 0, saudavel: 1 }

  has_one_attached :photo

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :gender, presence: true
  validates :sick, presence: true
  validates :race, presence: true


  def self.ransackable_attributes(auth_object = nil)
    ['name', 'race']
  end

  def self.ransackable_associations(auth_object = nil)
    ["name", "race"]
  end
end

app/controllers/animals_controller.rb
# frozen_string_literal: true

class AnimalsController < ApplicationController
  before_action :load_animals, only: %i[show edit update destroy]

  def index
    @q = Animal.ransack(params[:q])
    @animals = @q.result(distinct: true).page(params[:page])
  end

  def show; end

  def new
    @animal = Animal.new
  end

  def adoption
    @animal = Animal.find(params[:id])
    @animal.adopted!
    redirect_to animal_path, notice: 'Animal adotado com sucesso!'
  end


  def edit; end

  def create
    @animal = Animal.new(animal_params)

    if @animal.save
      redirect_to animals_path, notice: 'Animal cadastrado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @animal.update(animal_params)
      redirect_to animal_path, notice: 'Animal atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @animal.destroy
    redirect_to animals_path, notice: 'Excluido com sucesso.'
  end

  private

  def load_animals
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:name, :description, :race, :comment, :photo, :medicament, :gender, :sick, :history)
  end
end

app/views/animals/_form.html.erb
<%= form_for @animal, url: url, data: { turbo: :false } do |f| %>
  <div class="md:flex md:justify-between md:items-center">
    <div class="md:w-2/3">
      <%= label_tag :name, 'Nome', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.text_field :name,
                          autofocus: true,
                          class: 'input-form' %>

        <%= f.label :race, 'Raça', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.text_field :race,
                        autofocus: true,
                        class: 'input-form' %>

        <%= f.label :gender, 'Sexo', class: "block text-sm font-medium mb-2 ml-1 text-gray-700" %>
        <%= f.select :gender, { "Macho" => :macho, "Fêmea" => :fêmea }, { prompt: 'Selecione o sexo do animal' },
          class: "select-input mb-2" %>

        <%= f.label :sick, 'Saúde', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.select :sick, { "Doente" => :doente, "Saudável" => :saudavel }, { prompt: 'Selecione' },
          class: "select-input mb-2" %>


        <%= f.label :description, 'Descrição', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.text_area :description,
                      autofocus: true,
                      class: 'input-form' %>

        <%= f.label :history, 'História', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.text_area :history,
                      autofocus: true,
                      class: 'input-form' %>

        <%= f.label :comment, 'Observações', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.text_area :comment,
                        autofocus: true,
                          class: 'input-form' %>

        <%= f.label :medicament, 'Medicamentos', class: 'block text-sm font-medium mb-2 ml-1 text-gray-700' %>
        <%= f.text_area :medicament,
                        autofocus: true,
                          class: 'input-form' %>


        <%= f.label :photo, "Adicione uma foto", class: "md:text-left text-center block text-sm font-medium mb-2 ml-1 text-gray-700"%>
        <%= f.file_field :photo, class:"mr-auto border border-gray-300 rounded-lg p-2 w-full mb-2", data: { target: "image-preview.input", action: "image-preview#readURL" } %>
    </div>

    <div class="mx-auto p-8 hidden md:block">
      <h1 class="text-center text-gray-700 font-bold text-xl mb-2">Foto selecionada</h1>
      <div data-controller="image-preview">
        <%= image_tag('cachorro-sem-foto.png', class: "w-full md:h-96 rounded-lg", data: { target: "image-preview.output" }) %>
      </div>
    </div>
  </div>

  <div class="md:w-40">
    <div class="space-x-2 flex justify-center items-center md:justify-left">
        <% if @animal.id.present? %>
          <%= link_to "Voltar", animal_path, class:"button-secondary font-bold p-2" %>
        <% else %>
          <%= link_to "Voltar", animals_path, class:"button-secondary p-2 font-bold" %>
        <% end %>
        <%= f.submit "Concluido", class:"button-primary w-48" %>
    </div>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const input = document.querySelector("[data-target='image-preview.input']");
    const img = document.querySelector("[data-target='image-preview.output']");

    input.addEventListener("change", function() {
      if (this.files && this.files[0]) {
        const reader = new FileReader();
        reader.onload = function(e) {
          img.setAttribute("src", e.target.result);
        };
        reader.readAsDataURL(this.files[0]);
      }
    });
  });
</script>

app/views/animals/_search_bar.html.erb
 <div class="p-4">
  <label for="table-search" class="sr-only">Search</label>
  <div class="flex justify-end">
    <div class="relative mt-1">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
            clip-rule="evenodd"></path>
        </svg>
      </div>
      <%= search_form_for @q do |f| %>
        <%= f.search_field :name_or_race_cont, class: "search-input", placeholder: "Pesquisar..." %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animals/_search_input.html.erb
 <div class="p-4">
  <label for="table-search" class="sr-only">Search</label>
  <div class="flex justify-end">
    <div class="relative mt-1">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
            clip-rule="evenodd"></path>
        </svg>
      </div>
      <%= search_form_for @q do |f| %>
        <%= f.search_field :name_or_race_cont, class: "search-input", placeholder: "Pesquisar..." %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animals/_table.html.erb
<div class="relative overflow-x-auto">
  <table class="w-full md:text-sm text-left text-gray-500 shadow-lg rounded-lg text-xs">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3">
              Nome
          </th>
          <th scope="col" class="px-6 py-3">
              Raça
          </th>
            <th scope="col" class="px-6 py-3">
          </th>
            <th scope="col" class="px-6 py-3">
          </th>
        </tr>
    </thead>
    <tbody>
      <% @animals.each do |animal| %>
        <tr class="bg-white border-b">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
              <%= animal.name %>
          </th>
          <td class="px-6 py-4">
              <%= animal.race %>
          </td>
          <td class="px-6 py-4 text-end">
              <%= link_to animal_path(animal),
                class: 'font-semibold link-color hover:underline' do %>
                Visualizar
              <% end %>
          </td>
          <td class="px-6 py-4 text-end">
              <%= button_to animal_path(animal), method: :delete,
                class: 'text-red-500 hover:text-black hover:underline' do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/animals/edit.html.erb
<div class='bg-gray-100 rounded-lg space-y-4 w-full mx-auto'>
  <div class="bg-white rounded-lg p-2 shadow-lg">
    <h1 class="text-3xl font-bold ml-2 my-2">Alterar dados</h1>
  </div>
  <div class="bg-white rounded-lg p-2 shadow-lg">
    <%= render 'form', url: animal_path(@animal) %>
  </div>
</div>

app/views/animals/index.html.erb
<div class="w-full">
  <div class="flex justify-between bg-white items-center rounded-lg p-4">
    <div>
      <h1 class="text-3xl md:text-4xl font-bold">🐶 Animais</h1>
    </div>
    <div>
      <%= link_to "Adicionar animal", new_animal_path, class: "bg-black text-white md:p-2 text-xs p-1.5 rounded-lg" %>
    </div>
  </div>
  <div class="md:flex md:justify-beetween md:items-center ">
    <div class="hidden md:block">
      <%= paginate @animals %>
    </div>
    <div class="ml-auto">
      <%= render 'search_input' %>
    </div>
  </div>
    <%= render 'table' %>
  <div class="flex justify-center md:hidden">
    <%= paginate @animals, window: 1 %>
  </div>
</div>

app/views/animals/new.html.erb
<div class='bg-gray-100 rounded-lg space-y-4'>
  <div class="bg-white rounded-lg p-2 shadow-lg">
    <h1 class="text-3xl font-bold ml-2 my-2">Adicionar animal</h1>
  </div>
  <div class="bg-white rounded-lg p-2 shadow-lg">
    <%= render 'form', url: animals_path %>
  </div>
</div>

app/views/animals/show.html.erb
<div class="bg-gray-100">
 <div class="w-full text-white bg-main-color">
    <div class="container mx-auto my-5 p-5">
        <div class="md:flex no-wrap md:-mx-2 ">
            <div class="w-full md:w-3/12 md:mx-2 mb-2 ml-2">
                <div class="bg-white p-3 border-t-4 border-green-400">
                    <div class="image overflow-hidden text-black">
                        <% if @animal.photo.present? %>
                          <% ActiveStorage::Current.url_options = { host: request.base_url } %>
                          <%= image_tag @animal.photo.url, class: "min-w-full" %>
                        <% else %>
                          <%= image_tag("cachorro-sem-foto.png") %>
                        <% end %>
                    </div>
                    <h1 class="text-gray-900 font-bold text-xl leading-8 my-1"><%= @animal.name %></h1>
                    <p class="text-sm text-gray-500 hover:text-gray-600 leading-6"><%= @animal.description %></p>
                    <ul class="bg-gray-100 text-gray-600 hover:text-gray-700 hover:shadow py-2 px-3 mt-3 divide-y rounded shadow-sm">

                      <% if @animal.available? %>
                          <li class="flex items-center py-3">
                              <span>Status</span>
                              <span class="ml-auto">
                                  <span class="bg-green-500 py-1 px-2 rounded text-white text-sm">Disponível</span>
                              </span>
                          </li>
                          <li class="flex items-center py-3">
                              <span>Chegou em</span>
                              <span class="ml-auto"><%= @animal.created_at.strftime("%d/%m/%Y") %></span>
                          </li>
                      <% else %>
                          <li class="flex items-center py-3">
                              <span>Status</span>
                              <span class="ml-auto">
                                  <span class="bg-red-500 py-1 px-2 rounded text-white text-sm">Adotado</span>
                              </span>
                          </li>
                          <li class="flex items-center py-3">
                              <span>Adotado em</span>
                              <span class="ml-auto"><%= @animal.updated_at.strftime("%d/%m/%Y") %></span>
                          </li>
                      <% end %>
                    </ul>
                </div>
            </div>
            <div class="w-full md:w-9/12 mx-2 h-64">
                <div class="bg-white p-3 shadow-sm rounded-sm">
                    <div class="flex justify-between items-center space-x-2 font-semibold text-gray-900 leading-8">
                      <span class="tracking-wide ml-4 text-sm md:text-md">Sobre 🐕</span>
                      <div class="flex items-center space-x-2">
                      <%= link_to "Alterar dados", edit_animal_path, class: "text-xs p-1.5 md:p-2 bg-black text-white rounded-lg text-center" %>
                      <% if @animal.available? %>
                        <%= button_to "Adicionar adoção", adoption_animal_path(@animal), method: :patch, class: "text-xs p-2 bg-black text-white rounded-lg" %>
                      <% end %>
                      </div>
                    </div>
                    <div class="text-gray-700">
                        <div class="grid md:grid-cols-1 text-sm">
                            <div class="flex">
                                <div class="px-4 py-2 font-semibold">Nome:</div>
                                <div class=" py-2"><%= @animal.name.humanize.capitalize %></div>
                            </div>
                            <div class="flex">
                                <div class="px-4 py-2 font-semibold">Raça:</div>
                                <div class="py-2"><%= @animal.race.humanize.capitalize %></div>
                            </div>
                            <div class="flex">
                                <div class="px-4 py-2 font-semibold">Sexo:</div>
                                <div class=" py-2"><%= @animal.gender.humanize.capitalize %></div>
                            </div>
                            <div class="flex">
                                <div class="px-4 py-2 font-semibold">Saúde:</div>
                                <div class="py-2"><%= @animal.sick.humanize.capitalize %></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="my-4"></div>
                <div class="bg-white p-3 shadow-sm rounded-sm mb-2">
                    <div class="grid grid-cols-2">
                        <div>
                          <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8 mb-3">
                              <span class="tracking-wide">Medicamentos 💉</span>
                          </div>
                          <ul class="list-inside space-y-2">
                            <li>
                                <div class="text-gray-500 text-sm"><%= simple_format(@animal.medicament) %></div>
                            </li>
                          </ul>
                        </div>
                        <div>
                          <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8 mb-3">
                            <span class="tracking-wide">Observações 📔</span>
                          </div>
                          <ul class="list-inside space-y-2">
                            <% if @animal.comment.present? %>
                              <li>
                                <div class="text-gray-500 text-sm"><%= simple_format(@animal.comment) %></div>
                              </li>
                              <% else %>
                                <li>
                                  <div class="text-gray-400">Nenhuma observação.</div>
                              </li>
                            <% end %>
                          </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>